BOMB_FUSE = GetConVar("bomb_fuse"):GetInt()
BOMB_ARMTIME = GetConVar("bomb_armtime"):GetInt()
BOMB_DMGRAD = GetConVar("bomb_dmgrad"):GetInt()
BOMB_TEAM_ARM = GetConVar("bomb_team_arm"):GetInt()
BOMB_NOTIFY = GetConVar("bomb_notify"):GetInt()
BOMB_NUMTEAMS = GetConVar("bomb_numteams"):GetInt()